# Auto-generated from Minecraft 1.21.11+ Template
# Simple remaps: block_name -> texture_name (all faces same)
TEXTURE_REMAP = {
    "acacia_button": "acacia_planks",
    "acacia_door": "acacia_door_bottom",
    "acacia_fence": "acacia_planks",
    "acacia_fence_gate": "acacia_planks",
    "acacia_hanging_sign": "stripped_acacia_log",
    "acacia_pressure_plate": "acacia_planks",
    "acacia_sign": "acacia_planks",
    "acacia_slab": "acacia_planks",
    "acacia_stairs": "acacia_planks",
    "acacia_wall_hanging_sign": "stripped_acacia_log",
    "acacia_wall_sign": "acacia_planks",
    "acacia_wood": "acacia_log",
    "andesite_slab": "andesite",
    "andesite_stairs": "andesite",
    "andesite_wall": "andesite",
    "attached_melon_stem": "melon_stem",
    "attached_pumpkin_stem": "pumpkin_stem",
    "azalea": "azalea_plant",
    "bamboo": "bamboo_stalk",
    "bamboo_button": "bamboo_planks",
    "bamboo_door": "bamboo_door_bottom",
    "bamboo_fence": "bamboo_fence_particle",
    "bamboo_fence_gate": "bamboo_fence_gate_particle",
    "bamboo_hanging_sign": "bamboo_planks",
    "bamboo_mosaic_slab": "bamboo_mosaic",
    "bamboo_mosaic_stairs": "bamboo_mosaic",
    "bamboo_pressure_plate": "bamboo_planks",
    "bamboo_sapling": "bamboo_stage0",
    "bamboo_sign": "bamboo_planks",
    "bamboo_slab": "bamboo_planks",
    "bamboo_stairs": "bamboo_planks",
    "bamboo_wall_hanging_sign": "bamboo_planks",
    "bamboo_wall_sign": "bamboo_planks",
    "beacon": "glass",
    "beetroots": "beetroots_stage0",
    "bell": "bell_bottom",
    "big_dripleaf": "big_dripleaf_top",
    "birch_button": "birch_planks",
    "birch_door": "birch_door_bottom",
    "birch_fence": "birch_planks",
    "birch_fence_gate": "birch_planks",
    "birch_hanging_sign": "stripped_birch_log",
    "birch_pressure_plate": "birch_planks",
    "birch_sign": "birch_planks",
    "birch_slab": "birch_planks",
    "birch_stairs": "birch_planks",
    "birch_wall_hanging_sign": "stripped_birch_log",
    "birch_wall_sign": "birch_planks",
    "birch_wood": "birch_log",
    "black_banner": "oak_planks",
    "black_bed": "oak_planks",
    "black_candle_cake": "cake_side",
    "black_carpet": "black_wool",
    "black_stained_glass_pane": "black_stained_glass",
    "black_wall_banner": "oak_planks",
    "blackstone_slab": "blackstone",
    "blackstone_stairs": "blackstone",
    "blackstone_wall": "blackstone",
    "blue_banner": "oak_planks",
    "blue_bed": "oak_planks",
    "blue_candle_cake": "cake_side",
    "blue_carpet": "blue_wool",
    "blue_stained_glass_pane": "blue_stained_glass",
    "blue_wall_banner": "oak_planks",
    "brain_coral_wall_fan": "brain_coral_fan",
    "brick_slab": "bricks",
    "brick_stairs": "bricks",
    "brick_wall": "bricks",
    "brown_banner": "oak_planks",
    "brown_bed": "oak_planks",
    "brown_candle_cake": "cake_side",
    "brown_carpet": "brown_wool",
    "brown_stained_glass_pane": "brown_stained_glass",
    "brown_wall_banner": "oak_planks",
    "bubble_column": "water_still",
    "bubble_coral_wall_fan": "bubble_coral_fan",
    "cake": "cake_side",
    "calibrated_sculk_sensor": "sculk_sensor_bottom",
    "campfire": "campfire_log",
    "candle_cake": "cake_side",
    "carrots": "carrots_stage0",
    "cauldron": "cauldron_side",
    "cherry_button": "cherry_planks",
    "cherry_door": "cherry_door_bottom",
    "cherry_fence": "cherry_planks",
    "cherry_fence_gate": "cherry_planks",
    "cherry_hanging_sign": "stripped_cherry_log",
    "cherry_pressure_plate": "cherry_planks",
    "cherry_sign": "cherry_planks",
    "cherry_slab": "cherry_planks",
    "cherry_stairs": "cherry_planks",
    "cherry_wall_hanging_sign": "stripped_cherry_log",
    "cherry_wall_sign": "cherry_planks",
    "cherry_wood": "cherry_log",
    "chest": "oak_planks",
    "chipped_anvil": "anvil",
    "cobbled_deepslate_slab": "cobbled_deepslate",
    "cobbled_deepslate_stairs": "cobbled_deepslate",
    "cobbled_deepslate_wall": "cobbled_deepslate",
    "cobblestone_slab": "cobblestone",
    "cobblestone_stairs": "cobblestone",
    "cobblestone_wall": "cobblestone",
    "cocoa": "cocoa_stage0",
    "composter": "composter_side",
    "copper_chest": "copper_block",
    "copper_door": "copper_door_bottom",
    "copper_golem_statue": "copper_block",
    "copper_wall_torch": "copper_torch",
    "creeper_head": "soul_sand",
    "creeper_wall_head": "soul_sand",
    "crimson_button": "crimson_planks",
    "crimson_door": "crimson_door_bottom",
    "crimson_fence": "crimson_planks",
    "crimson_fence_gate": "crimson_planks",
    "crimson_hanging_sign": "stripped_crimson_stem",
    "crimson_hyphae": "crimson_stem",
    "crimson_pressure_plate": "crimson_planks",
    "crimson_sign": "crimson_planks",
    "crimson_slab": "crimson_planks",
    "crimson_stairs": "crimson_planks",
    "crimson_wall_hanging_sign": "stripped_crimson_stem",
    "crimson_wall_sign": "crimson_planks",
    "cut_copper_slab": "cut_copper",
    "cut_copper_stairs": "cut_copper",
    "cut_red_sandstone_slab": "cut_red_sandstone",
    "cut_sandstone_slab": "cut_sandstone",
    "cyan_banner": "oak_planks",
    "cyan_bed": "oak_planks",
    "cyan_candle_cake": "cake_side",
    "cyan_carpet": "cyan_wool",
    "cyan_stained_glass_pane": "cyan_stained_glass",
    "cyan_wall_banner": "oak_planks",
    "damaged_anvil": "anvil",
    "dark_oak_button": "dark_oak_planks",
    "dark_oak_door": "dark_oak_door_bottom",
    "dark_oak_fence": "dark_oak_planks",
    "dark_oak_fence_gate": "dark_oak_planks",
    "dark_oak_hanging_sign": "stripped_dark_oak_log",
    "dark_oak_pressure_plate": "dark_oak_planks",
    "dark_oak_sign": "dark_oak_planks",
    "dark_oak_slab": "dark_oak_planks",
    "dark_oak_stairs": "dark_oak_planks",
    "dark_oak_wall_hanging_sign": "stripped_dark_oak_log",
    "dark_oak_wall_sign": "dark_oak_planks",
    "dark_oak_wood": "dark_oak_log",
    "dark_prismarine_slab": "dark_prismarine",
    "dark_prismarine_stairs": "dark_prismarine",
    "daylight_detector": "daylight_detector_top",
    "dead_brain_coral_wall_fan": "dead_brain_coral_fan",
    "dead_bubble_coral_wall_fan": "dead_bubble_coral_fan",
    "dead_fire_coral_wall_fan": "dead_fire_coral_fan",
    "dead_horn_coral_wall_fan": "dead_horn_coral_fan",
    "dead_tube_coral_wall_fan": "dead_tube_coral_fan",
    "decorated_pot": "terracotta",
    "deepslate_brick_slab": "deepslate_bricks",
    "deepslate_brick_stairs": "deepslate_bricks",
    "deepslate_brick_wall": "deepslate_bricks",
    "deepslate_tile_slab": "deepslate_tiles",
    "deepslate_tile_stairs": "deepslate_tiles",
    "deepslate_tile_wall": "deepslate_tiles",
    "diorite_slab": "diorite",
    "diorite_stairs": "diorite",
    "diorite_wall": "diorite",
    "dirt_path": "dirt",
    "dragon_head": "soul_sand",
    "dragon_wall_head": "soul_sand",
    "enchanting_table": "enchanting_table_bottom",
    "end_gateway": "obsidian",
    "end_portal": "obsidian",
    "end_portal_frame": "end_portal_frame_side",
    "end_stone_brick_slab": "end_stone_bricks",
    "end_stone_brick_stairs": "end_stone_bricks",
    "end_stone_brick_wall": "end_stone_bricks",
    "ender_chest": "obsidian",
    "exposed_copper_chest": "exposed_copper",
    "exposed_copper_door": "exposed_copper_door_bottom",
    "exposed_copper_golem_statue": "exposed_copper",
    "exposed_cut_copper_slab": "exposed_cut_copper",
    "exposed_cut_copper_stairs": "exposed_cut_copper",
    "farmland": "dirt",
    "fire": "fire_0",
    "fire_coral_wall_fan": "fire_coral_fan",
    "flowering_azalea": "azalea_plant",
    "frosted_ice": "frosted_ice_0",
    "glass_pane": "glass",
    "glow_item_frame": "birch_planks",
    "granite_slab": "granite",
    "granite_stairs": "granite",
    "granite_wall": "granite",
    "gray_banner": "oak_planks",
    "gray_bed": "oak_planks",
    "gray_candle_cake": "cake_side",
    "gray_carpet": "gray_wool",
    "gray_stained_glass_pane": "gray_stained_glass",
    "gray_wall_banner": "oak_planks",
    "green_banner": "oak_planks",
    "green_bed": "oak_planks",
    "green_candle_cake": "cake_side",
    "green_carpet": "green_wool",
    "green_stained_glass_pane": "green_stained_glass",
    "green_wall_banner": "oak_planks",
    "grindstone": "grindstone_side",
    "heavy_weighted_pressure_plate": "iron_block",
    "honey_block": "honey_block_bottom",
    "hopper": "hopper_outside",
    "horn_coral_wall_fan": "horn_coral_fan",
    "infested_chiseled_stone_bricks": "chiseled_stone_bricks",
    "infested_cobblestone": "cobblestone",
    "infested_cracked_stone_bricks": "cracked_stone_bricks",
    "infested_mossy_stone_bricks": "mossy_stone_bricks",
    "infested_stone": "stone",
    "infested_stone_bricks": "stone_bricks",
    "iron_door": "iron_door_bottom",
    "item_frame": "birch_planks",
    "jungle_button": "jungle_planks",
    "jungle_door": "jungle_door_bottom",
    "jungle_fence": "jungle_planks",
    "jungle_fence_gate": "jungle_planks",
    "jungle_hanging_sign": "stripped_jungle_log",
    "jungle_pressure_plate": "jungle_planks",
    "jungle_sign": "jungle_planks",
    "jungle_slab": "jungle_planks",
    "jungle_stairs": "jungle_planks",
    "jungle_wall_hanging_sign": "stripped_jungle_log",
    "jungle_wall_sign": "jungle_planks",
    "jungle_wood": "jungle_log",
    "kelp_plant": "kelp",
    "large_fern": "large_fern_bottom",
    "lava": "lava_still",
    "lava_cauldron": "cauldron_side",
    "lectern": "lectern_sides",
    "lever": "cobblestone",
    "light": "light_00",
    "light_blue_banner": "oak_planks",
    "light_blue_bed": "oak_planks",
    "light_blue_candle_cake": "cake_side",
    "light_blue_carpet": "light_blue_wool",
    "light_blue_stained_glass_pane": "light_blue_stained_glass",
    "light_blue_wall_banner": "oak_planks",
    "light_gray_banner": "oak_planks",
    "light_gray_bed": "oak_planks",
    "light_gray_candle_cake": "cake_side",
    "light_gray_carpet": "light_gray_wool",
    "light_gray_stained_glass_pane": "light_gray_stained_glass",
    "light_gray_wall_banner": "oak_planks",
    "light_weighted_pressure_plate": "gold_block",
    "lilac": "lilac_bottom",
    "lime_banner": "oak_planks",
    "lime_bed": "oak_planks",
    "lime_candle_cake": "cake_side",
    "lime_carpet": "lime_wool",
    "lime_stained_glass_pane": "lime_stained_glass",
    "lime_wall_banner": "oak_planks",
    "magenta_banner": "oak_planks",
    "magenta_bed": "oak_planks",
    "magenta_candle_cake": "cake_side",
    "magenta_carpet": "magenta_wool",
    "magenta_stained_glass_pane": "magenta_stained_glass",
    "magenta_wall_banner": "oak_planks",
    "magma_block": "magma",
    "mangrove_button": "mangrove_planks",
    "mangrove_door": "mangrove_door_bottom",
    "mangrove_fence": "mangrove_planks",
    "mangrove_fence_gate": "mangrove_planks",
    "mangrove_hanging_sign": "stripped_mangrove_log",
    "mangrove_pressure_plate": "mangrove_planks",
    "mangrove_roots": "mangrove_roots_side",
    "mangrove_sign": "mangrove_planks",
    "mangrove_slab": "mangrove_planks",
    "mangrove_stairs": "mangrove_planks",
    "mangrove_wall_hanging_sign": "stripped_mangrove_log",
    "mangrove_wall_sign": "mangrove_planks",
    "mangrove_wood": "mangrove_log",
    "moss_carpet": "moss_block",
    "mossy_cobblestone_slab": "mossy_cobblestone",
    "mossy_cobblestone_stairs": "mossy_cobblestone",
    "mossy_cobblestone_wall": "mossy_cobblestone",
    "mossy_stone_brick_slab": "mossy_stone_bricks",
    "mossy_stone_brick_stairs": "mossy_stone_bricks",
    "mossy_stone_brick_wall": "mossy_stone_bricks",
    "moving_piston": "piston_side",
    "mud_brick_slab": "mud_bricks",
    "mud_brick_stairs": "mud_bricks",
    "mud_brick_wall": "mud_bricks",
    "nether_brick_fence": "nether_bricks",
    "nether_brick_slab": "nether_bricks",
    "nether_brick_stairs": "nether_bricks",
    "nether_brick_wall": "nether_bricks",
    "nether_wart": "nether_wart_stage0",
    "oak_button": "oak_planks",
    "oak_door": "oak_door_bottom",
    "oak_fence": "oak_planks",
    "oak_fence_gate": "oak_planks",
    "oak_hanging_sign": "stripped_oak_log",
    "oak_pressure_plate": "oak_planks",
    "oak_sign": "oak_planks",
    "oak_slab": "oak_planks",
    "oak_stairs": "oak_planks",
    "oak_wall_hanging_sign": "stripped_oak_log",
    "oak_wall_sign": "oak_planks",
    "oak_wood": "oak_log",
    "orange_banner": "oak_planks",
    "orange_bed": "oak_planks",
    "orange_candle_cake": "cake_side",
    "orange_carpet": "orange_wool",
    "orange_stained_glass_pane": "orange_stained_glass",
    "orange_wall_banner": "oak_planks",
    "oxidized_copper_chest": "oxidized_copper",
    "oxidized_copper_door": "oxidized_copper_door_bottom",
    "oxidized_copper_golem_statue": "oxidized_copper",
    "oxidized_cut_copper_slab": "oxidized_cut_copper",
    "oxidized_cut_copper_stairs": "oxidized_cut_copper",
    "pale_oak_button": "pale_oak_planks",
    "pale_oak_door": "pale_oak_door_bottom",
    "pale_oak_fence": "pale_oak_planks",
    "pale_oak_fence_gate": "pale_oak_planks",
    "pale_oak_hanging_sign": "stripped_pale_oak_log",
    "pale_oak_pressure_plate": "pale_oak_planks",
    "pale_oak_sign": "pale_oak_planks",
    "pale_oak_slab": "pale_oak_planks",
    "pale_oak_stairs": "pale_oak_planks",
    "pale_oak_wall_hanging_sign": "stripped_pale_oak_log",
    "pale_oak_wall_sign": "pale_oak_planks",
    "pale_oak_wood": "pale_oak_log",
    "peony": "peony_bottom",
    "petrified_oak_slab": "oak_planks",
    "piglin_head": "soul_sand",
    "piglin_wall_head": "soul_sand",
    "pink_banner": "oak_planks",
    "pink_bed": "oak_planks",
    "pink_candle_cake": "cake_side",
    "pink_carpet": "pink_wool",
    "pink_stained_glass_pane": "pink_stained_glass",
    "pink_wall_banner": "oak_planks",
    "piston_head": "piston_top",
    "pitcher_crop": "pitcher_crop_top",
    "pitcher_plant": "pitcher_crop_bottom_stage_4",
    "player_head": "soul_sand",
    "player_wall_head": "soul_sand",
    "pointed_dripstone": "pointed_dripstone_down_base",
    "polished_andesite_slab": "polished_andesite",
    "polished_andesite_stairs": "polished_andesite",
    "polished_blackstone_brick_slab": "polished_blackstone_bricks",
    "polished_blackstone_brick_stairs": "polished_blackstone_bricks",
    "polished_blackstone_brick_wall": "polished_blackstone_bricks",
    "polished_blackstone_button": "polished_blackstone",
    "polished_blackstone_pressure_plate": "polished_blackstone",
    "polished_blackstone_slab": "polished_blackstone",
    "polished_blackstone_stairs": "polished_blackstone",
    "polished_blackstone_wall": "polished_blackstone",
    "polished_deepslate_slab": "polished_deepslate",
    "polished_deepslate_stairs": "polished_deepslate",
    "polished_deepslate_wall": "polished_deepslate",
    "polished_diorite_slab": "polished_diorite",
    "polished_diorite_stairs": "polished_diorite",
    "polished_granite_slab": "polished_granite",
    "polished_granite_stairs": "polished_granite",
    "polished_tuff_slab": "polished_tuff",
    "polished_tuff_stairs": "polished_tuff",
    "polished_tuff_wall": "polished_tuff",
    "potatoes": "potatoes_stage0",
    "potted_acacia_sapling": "flower_pot",
    "potted_allium": "flower_pot",
    "potted_azalea_bush": "flower_pot",
    "potted_azure_bluet": "flower_pot",
    "potted_bamboo": "flower_pot",
    "potted_birch_sapling": "flower_pot",
    "potted_blue_orchid": "flower_pot",
    "potted_brown_mushroom": "flower_pot",
    "potted_cactus": "flower_pot",
    "potted_cherry_sapling": "flower_pot",
    "potted_closed_eyeblossom": "flower_pot",
    "potted_cornflower": "flower_pot",
    "potted_crimson_fungus": "flower_pot",
    "potted_crimson_roots": "flower_pot",
    "potted_dandelion": "flower_pot",
    "potted_dark_oak_sapling": "flower_pot",
    "potted_dead_bush": "flower_pot",
    "potted_fern": "flower_pot",
    "potted_flowering_azalea_bush": "flower_pot",
    "potted_jungle_sapling": "flower_pot",
    "potted_lily_of_the_valley": "flower_pot",
    "potted_mangrove_propagule": "flower_pot",
    "potted_oak_sapling": "flower_pot",
    "potted_open_eyeblossom": "flower_pot",
    "potted_orange_tulip": "flower_pot",
    "potted_oxeye_daisy": "flower_pot",
    "potted_pale_oak_sapling": "flower_pot",
    "potted_pink_tulip": "flower_pot",
    "potted_poppy": "flower_pot",
    "potted_red_mushroom": "flower_pot",
    "potted_red_tulip": "flower_pot",
    "potted_spruce_sapling": "flower_pot",
    "potted_torchflower": "flower_pot",
    "potted_warped_fungus": "flower_pot",
    "potted_warped_roots": "flower_pot",
    "potted_white_tulip": "flower_pot",
    "potted_wither_rose": "flower_pot",
    "powder_snow_cauldron": "cauldron_side",
    "prismarine_brick_slab": "prismarine_bricks",
    "prismarine_brick_stairs": "prismarine_bricks",
    "prismarine_slab": "prismarine",
    "prismarine_stairs": "prismarine",
    "prismarine_wall": "prismarine",
    "purple_banner": "oak_planks",
    "purple_bed": "oak_planks",
    "purple_candle_cake": "cake_side",
    "purple_carpet": "purple_wool",
    "purple_stained_glass_pane": "purple_stained_glass",
    "purple_wall_banner": "oak_planks",
    "purpur_slab": "purpur_block",
    "purpur_stairs": "purpur_block",
    "quartz_slab": "quartz_block_side",
    "quartz_stairs": "quartz_block_side",
    "red_banner": "oak_planks",
    "red_bed": "oak_planks",
    "red_candle_cake": "cake_side",
    "red_carpet": "red_wool",
    "red_nether_brick_slab": "red_nether_bricks",
    "red_nether_brick_stairs": "red_nether_bricks",
    "red_nether_brick_wall": "red_nether_bricks",
    "red_sandstone_slab": "red_sandstone",
    "red_sandstone_stairs": "red_sandstone",
    "red_sandstone_wall": "red_sandstone",
    "red_stained_glass_pane": "red_stained_glass",
    "red_wall_banner": "oak_planks",
    "redstone_torch": "redstone_torch_off",
    "redstone_wall_torch": "redstone_torch_off",
    "redstone_wire": "redstone_dust_dot",
    "resin_brick_slab": "resin_bricks",
    "resin_brick_stairs": "resin_bricks",
    "resin_brick_wall": "resin_bricks",
    "rose_bush": "rose_bush_bottom",
    "sandstone_slab": "sandstone",
    "sandstone_stairs": "sandstone",
    "sandstone_wall": "sandstone",
    "scaffolding": "scaffolding_top",
    "sculk_sensor": "sculk_sensor_bottom",
    "sculk_shrieker": "sculk_shrieker_bottom",
    "skeleton_skull": "soul_sand",
    "skeleton_wall_skull": "soul_sand",
    "small_dripleaf": "big_dripleaf_stem",
    "smooth_quartz": "quartz_block_bottom",
    "smooth_quartz_slab": "quartz_block_bottom",
    "smooth_quartz_stairs": "quartz_block_bottom",
    "smooth_red_sandstone": "red_sandstone_top",
    "smooth_red_sandstone_slab": "red_sandstone_top",
    "smooth_red_sandstone_stairs": "red_sandstone_top",
    "smooth_sandstone": "sandstone_top",
    "smooth_sandstone_slab": "sandstone_top",
    "smooth_sandstone_stairs": "sandstone_top",
    "smooth_stone_slab": "smooth_stone_slab_side",
    "snow_block": "snow",
    "soul_campfire": "campfire_log",
    "soul_fire": "soul_fire_0",
    "soul_wall_torch": "soul_torch",
    "spruce_button": "spruce_planks",
    "spruce_door": "spruce_door_bottom",
    "spruce_fence": "spruce_planks",
    "spruce_fence_gate": "spruce_planks",
    "spruce_hanging_sign": "stripped_spruce_log",
    "spruce_pressure_plate": "spruce_planks",
    "spruce_sign": "spruce_planks",
    "spruce_slab": "spruce_planks",
    "spruce_stairs": "spruce_planks",
    "spruce_wall_hanging_sign": "stripped_spruce_log",
    "spruce_wall_sign": "spruce_planks",
    "spruce_wood": "spruce_log",
    "stone_brick_slab": "stone_bricks",
    "stone_brick_stairs": "stone_bricks",
    "stone_brick_wall": "stone_bricks",
    "stone_button": "stone",
    "stone_pressure_plate": "stone",
    "stone_slab": "stone",
    "stone_stairs": "stone",
    "stonecutter": "stonecutter_bottom",
    "stripped_acacia_wood": "stripped_acacia_log",
    "stripped_birch_wood": "stripped_birch_log",
    "stripped_cherry_wood": "stripped_cherry_log",
    "stripped_crimson_hyphae": "stripped_crimson_stem",
    "stripped_dark_oak_wood": "stripped_dark_oak_log",
    "stripped_jungle_wood": "stripped_jungle_log",
    "stripped_mangrove_wood": "stripped_mangrove_log",
    "stripped_oak_wood": "stripped_oak_log",
    "stripped_pale_oak_wood": "stripped_pale_oak_log",
    "stripped_spruce_wood": "stripped_spruce_log",
    "stripped_warped_hyphae": "stripped_warped_stem",
    "structure_block": "structure_block_corner",
    "sunflower": "sunflower_bottom",
    "suspicious_gravel": "suspicious_gravel_0",
    "suspicious_sand": "suspicious_sand_0",
    "sweet_berry_bush": "sweet_berry_bush_stage0",
    "tall_grass": "tall_grass_bottom",
    "tall_seagrass": "tall_seagrass_bottom",
    "test_block": "test_block_accept",
    "torchflower_crop": "torchflower_crop_stage0",
    "trapped_chest": "oak_planks",
    "tripwire_hook": "oak_planks",
    "tube_coral_wall_fan": "tube_coral_fan",
    "tuff_brick_slab": "tuff_bricks",
    "tuff_brick_stairs": "tuff_bricks",
    "tuff_brick_wall": "tuff_bricks",
    "tuff_slab": "tuff",
    "tuff_stairs": "tuff",
    "tuff_wall": "tuff",
    "wall_torch": "torch",
    "warped_button": "warped_planks",
    "warped_door": "warped_door_bottom",
    "warped_fence": "warped_planks",
    "warped_fence_gate": "warped_planks",
    "warped_hanging_sign": "stripped_warped_stem",
    "warped_hyphae": "warped_stem",
    "warped_pressure_plate": "warped_planks",
    "warped_sign": "warped_planks",
    "warped_slab": "warped_planks",
    "warped_stairs": "warped_planks",
    "warped_wall_hanging_sign": "stripped_warped_stem",
    "warped_wall_sign": "warped_planks",
    "water": "water_still",
    "water_flow": "water_flow",
    "water_cauldron": "cauldron_side",
    "waxed_chiseled_copper": "chiseled_copper",
    "waxed_copper_bars": "copper_bars",
    "waxed_copper_block": "copper_block",
    "waxed_copper_bulb": "copper_bulb",
    "waxed_copper_chain": "copper_chain",
    "waxed_copper_chest": "copper_block",
    "waxed_copper_door": "copper_door_bottom",
    "waxed_copper_golem_statue": "copper_block",
    "waxed_copper_grate": "copper_grate",
    "waxed_copper_lantern": "copper_lantern",
    "waxed_copper_trapdoor": "copper_trapdoor",
    "waxed_cut_copper": "cut_copper",
    "waxed_cut_copper_slab": "cut_copper",
    "waxed_cut_copper_stairs": "cut_copper",
    "waxed_exposed_chiseled_copper": "exposed_chiseled_copper",
    "waxed_exposed_copper": "exposed_copper",
    "waxed_exposed_copper_bars": "exposed_copper_bars",
    "waxed_exposed_copper_bulb": "exposed_copper_bulb",
    "waxed_exposed_copper_chain": "exposed_copper_chain",
    "waxed_exposed_copper_chest": "exposed_copper",
    "waxed_exposed_copper_door": "exposed_copper_door_bottom",
    "waxed_exposed_copper_golem_statue": "exposed_copper",
    "waxed_exposed_copper_grate": "exposed_copper_grate",
    "waxed_exposed_copper_lantern": "exposed_copper_lantern",
    "waxed_exposed_copper_trapdoor": "exposed_copper_trapdoor",
    "waxed_exposed_cut_copper": "exposed_cut_copper",
    "waxed_exposed_cut_copper_slab": "exposed_cut_copper",
    "waxed_exposed_cut_copper_stairs": "exposed_cut_copper",
    "waxed_exposed_lightning_rod": "exposed_lightning_rod",
    "waxed_lightning_rod": "lightning_rod",
    "waxed_oxidized_chiseled_copper": "oxidized_chiseled_copper",
    "waxed_oxidized_copper": "oxidized_copper",
    "waxed_oxidized_copper_bars": "oxidized_copper_bars",
    "waxed_oxidized_copper_bulb": "oxidized_copper_bulb",
    "waxed_oxidized_copper_chain": "oxidized_copper_chain",
    "waxed_oxidized_copper_chest": "oxidized_copper",
    "waxed_oxidized_copper_door": "oxidized_copper_door_bottom",
    "waxed_oxidized_copper_golem_statue": "oxidized_copper",
    "waxed_oxidized_copper_grate": "oxidized_copper_grate",
    "waxed_oxidized_copper_lantern": "oxidized_copper_lantern",
    "waxed_oxidized_copper_trapdoor": "oxidized_copper_trapdoor",
    "waxed_oxidized_cut_copper": "oxidized_cut_copper",
    "waxed_oxidized_cut_copper_slab": "oxidized_cut_copper",
    "waxed_oxidized_cut_copper_stairs": "oxidized_cut_copper",
    "waxed_oxidized_lightning_rod": "oxidized_lightning_rod",
    "waxed_weathered_chiseled_copper": "weathered_chiseled_copper",
    "waxed_weathered_copper": "weathered_copper",
    "waxed_weathered_copper_bars": "weathered_copper_bars",
    "waxed_weathered_copper_bulb": "weathered_copper_bulb",
    "waxed_weathered_copper_chain": "weathered_copper_chain",
    "waxed_weathered_copper_chest": "weathered_copper",
    "waxed_weathered_copper_door": "weathered_copper_door_bottom",
    "waxed_weathered_copper_golem_statue": "weathered_copper",
    "waxed_weathered_copper_grate": "weathered_copper_grate",
    "waxed_weathered_copper_lantern": "weathered_copper_lantern",
    "waxed_weathered_copper_trapdoor": "weathered_copper_trapdoor",
    "waxed_weathered_cut_copper": "weathered_cut_copper",
    "waxed_weathered_cut_copper_slab": "weathered_cut_copper",
    "waxed_weathered_cut_copper_stairs": "weathered_cut_copper",
    "waxed_weathered_lightning_rod": "weathered_lightning_rod",
    "weathered_copper_chest": "weathered_copper",
    "weathered_copper_door": "weathered_copper_door_bottom",
    "weathered_copper_golem_statue": "weathered_copper",
    "weathered_cut_copper_slab": "weathered_cut_copper",
    "weathered_cut_copper_stairs": "weathered_cut_copper",
    "wheat": "wheat_stage0",
    "white_banner": "oak_planks",
    "white_bed": "oak_planks",
    "white_candle_cake": "cake_side",
    "white_carpet": "white_wool",
    "white_stained_glass_pane": "white_stained_glass",
    "white_wall_banner": "oak_planks",
    "wither_skeleton_skull": "soul_sand",
    "wither_skeleton_wall_skull": "soul_sand",
    "yellow_banner": "oak_planks",
    "yellow_bed": "oak_planks",
    "yellow_candle_cake": "cake_side",
    "yellow_carpet": "yellow_wool",
    "yellow_stained_glass_pane": "yellow_stained_glass",
    "yellow_wall_banner": "oak_planks",
    "zombie_head": "soul_sand",
    "zombie_wall_head": "soul_sand",
}

# Multi-face texture map: block_name -> {face_dir: texture_name}
FACE_TEXTURE_MAP = {
    "acacia_log": {'+y': 'acacia_log_top', '-y': 'acacia_log_top', '-z': 'acacia_log', '+z': 'acacia_log', '+x': 'acacia_log', '-x': 'acacia_log'},
    "ancient_debris": {'+y': 'ancient_debris_top', '-y': 'ancient_debris_top', '-z': 'ancient_debris_side', '+z': 'ancient_debris_side', '+x': 'ancient_debris_side', '-x': 'ancient_debris_side'},
    "bamboo_block": {'+y': 'bamboo_block', '-y': 'bamboo_block', '-z': 'bamboo_block', '+z': 'bamboo_block', '+x': 'bamboo_block_top', '-x': 'bamboo_block_top'},
    "barrel": {'+y': 'barrel_top', '-y': 'barrel_bottom', '-z': 'barrel_side', '+z': 'barrel_side', '+x': 'barrel_side', '-x': 'barrel_side'},
    "basalt": {'+y': 'basalt_top', '-y': 'basalt_top', '-z': 'basalt_side', '+z': 'basalt_side', '+x': 'basalt_side', '-x': 'basalt_side'},
    "bee_nest": {'+y': 'bee_nest_top', '-y': 'bee_nest_bottom', '-z': 'bee_nest_front', '+z': 'bee_nest_side', '+x': 'bee_nest_side', '-x': 'bee_nest_side'},
    "beehive": {'+y': 'beehive_end', '-y': 'beehive_end', '-z': 'beehive_front', '+z': 'beehive_side', '+x': 'beehive_side', '-x': 'beehive_side'},
    "birch_log": {'+y': 'birch_log_top', '-y': 'birch_log_top', '-z': 'birch_log', '+z': 'birch_log', '+x': 'birch_log', '-x': 'birch_log'},
    "blackstone": {'+y': 'blackstone_top', '-y': 'blackstone_top', '-z': 'blackstone', '+z': 'blackstone', '+x': 'blackstone', '-x': 'blackstone'},
    "blast_furnace": {'+y': 'blast_furnace_top', '-y': 'blast_furnace_top', '-z': 'blast_furnace_front', '+z': 'blast_furnace_side', '+x': 'blast_furnace_side', '-x': 'blast_furnace_side'},
    "bone_block": {'+y': 'bone_block_top', '-y': 'bone_block_top', '-z': 'bone_block_side', '+z': 'bone_block_side', '+x': 'bone_block_side', '-x': 'bone_block_side'},
    "bookshelf": {'+y': 'oak_planks', '-y': 'oak_planks', '-z': 'bookshelf', '+z': 'bookshelf', '+x': 'bookshelf', '-x': 'bookshelf'},
    "cactus": {'+y': 'cactus_top', '-y': 'cactus_bottom'},
    "cartography_table": {'+y': 'cartography_table_top', '-y': 'dark_oak_planks', '-z': 'cartography_table_side3', '+z': 'cartography_table_side1', '+x': 'cartography_table_side3', '-x': 'cartography_table_side2'},
    "carved_pumpkin": {'+y': 'pumpkin_top', '-y': 'pumpkin_top', '-z': 'carved_pumpkin', '+z': 'pumpkin_side', '+x': 'pumpkin_side', '-x': 'pumpkin_side'},
    "chain_command_block": {'+y': 'chain_command_block_side', '-y': 'chain_command_block_side', '-z': 'chain_command_block_front', '+z': 'chain_command_block_back', '+x': 'chain_command_block_side', '-x': 'chain_command_block_side'},
    "cherry_log": {'+y': 'cherry_log', '-y': 'cherry_log', '-z': 'cherry_log', '+z': 'cherry_log', '+x': 'cherry_log_top', '-x': 'cherry_log_top'},
    "chiseled_bookshelf": {'+y': 'chiseled_bookshelf_top', '-y': 'chiseled_bookshelf_top', '+z': 'chiseled_bookshelf_side', '+x': 'chiseled_bookshelf_side', '-x': 'chiseled_bookshelf_side'},
    "chiseled_quartz_block": {'+y': 'chiseled_quartz_block_top', '-y': 'chiseled_quartz_block_top', '-z': 'chiseled_quartz_block', '+z': 'chiseled_quartz_block', '+x': 'chiseled_quartz_block', '-x': 'chiseled_quartz_block'},
    "chiseled_red_sandstone": {'+y': 'red_sandstone_top', '-y': 'red_sandstone_top', '-z': 'chiseled_red_sandstone', '+z': 'chiseled_red_sandstone', '+x': 'chiseled_red_sandstone', '-x': 'chiseled_red_sandstone'},
    "chiseled_sandstone": {'+y': 'sandstone_top', '-y': 'sandstone_top', '-z': 'chiseled_sandstone', '+z': 'chiseled_sandstone', '+x': 'chiseled_sandstone', '-x': 'chiseled_sandstone'},
    "chiseled_tuff": {'+y': 'chiseled_tuff_top', '-y': 'chiseled_tuff_top', '-z': 'chiseled_tuff', '+z': 'chiseled_tuff', '+x': 'chiseled_tuff', '-x': 'chiseled_tuff'},
    "chiseled_tuff_bricks": {'+y': 'chiseled_tuff_bricks_top', '-y': 'chiseled_tuff_bricks_top', '-z': 'chiseled_tuff_bricks', '+z': 'chiseled_tuff_bricks', '+x': 'chiseled_tuff_bricks', '-x': 'chiseled_tuff_bricks'},
    "command_block": {'+y': 'command_block_side', '-y': 'command_block_side', '-z': 'command_block_front', '+z': 'command_block_back', '+x': 'command_block_side', '-x': 'command_block_side'},
    "crafter": {'+y': 'crafter_top', '-y': 'crafter_bottom', '-z': 'crafter_north', '+z': 'crafter_south', '+x': 'crafter_east', '-x': 'crafter_west'},
    "crafting_table": {'+y': 'crafting_table_top', '-y': 'oak_planks', '-z': 'crafting_table_front', '+z': 'crafting_table_side', '+x': 'crafting_table_side', '-x': 'crafting_table_front'},
    "creaking_heart": {'+y': 'creaking_heart_top_awake', '-y': 'creaking_heart_top_awake', '-z': 'creaking_heart_awake', '+z': 'creaking_heart_awake', '+x': 'creaking_heart_awake', '-x': 'creaking_heart_awake'},
    "crimson_nylium": {'+y': 'crimson_nylium', '-y': 'netherrack', '-z': 'crimson_nylium_side', '+z': 'crimson_nylium_side', '+x': 'crimson_nylium_side', '-x': 'crimson_nylium_side'},
    "crimson_stem": {'+y': 'crimson_stem_top', '-y': 'crimson_stem_top', '-z': 'crimson_stem', '+z': 'crimson_stem', '+x': 'crimson_stem', '-x': 'crimson_stem'},
    "cut_red_sandstone": {'+y': 'red_sandstone_top', '-y': 'red_sandstone_top', '-z': 'cut_red_sandstone', '+z': 'cut_red_sandstone', '+x': 'cut_red_sandstone', '-x': 'cut_red_sandstone'},
    "cut_sandstone": {'+y': 'sandstone_top', '-y': 'sandstone_top', '-z': 'cut_sandstone', '+z': 'cut_sandstone', '+x': 'cut_sandstone', '-x': 'cut_sandstone'},
    "dark_oak_log": {'+y': 'dark_oak_log_top', '-y': 'dark_oak_log_top', '-z': 'dark_oak_log', '+z': 'dark_oak_log', '+x': 'dark_oak_log', '-x': 'dark_oak_log'},
    "deepslate": {'+y': 'deepslate_top', '-y': 'deepslate_top', '-z': 'deepslate', '+z': 'deepslate', '+x': 'deepslate', '-x': 'deepslate'},
    "dispenser": {'+y': 'dispenser_front_vertical', '-y': 'furnace_top', '-z': 'furnace_top', '+z': 'furnace_top', '+x': 'furnace_top', '-x': 'furnace_top'},
    "dried_ghast": {'-z': 'dried_ghast_hydration_0_north', '+z': 'dried_ghast_hydration_0_south', '+x': 'dried_ghast_hydration_0_east', '-x': 'dried_ghast_hydration_0_west'},
    "dried_kelp_block": {'+y': 'dried_kelp_top', '-y': 'dried_kelp_bottom', '-z': 'dried_kelp_side', '+z': 'dried_kelp_side', '+x': 'dried_kelp_side', '-x': 'dried_kelp_side'},
    "dropper": {'+y': 'dropper_front_vertical', '-y': 'furnace_top', '-z': 'furnace_top', '+z': 'furnace_top', '+x': 'furnace_top', '-x': 'furnace_top'},
    "fletching_table": {'+y': 'fletching_table_top', '-y': 'birch_planks', '-z': 'fletching_table_front', '+z': 'fletching_table_front', '+x': 'fletching_table_side', '-x': 'fletching_table_side'},
    "furnace": {'+y': 'furnace_top', '-y': 'furnace_top', '-z': 'furnace_front', '+z': 'furnace_side', '+x': 'furnace_side', '-x': 'furnace_side'},
    "grass_block": {'+y': 'grass_block_top', '-y': 'dirt', '-z': 'grass_block_side', '+z': 'grass_block_side', '+x': 'grass_block_side', '-x': 'grass_block_side'},
    "hay_block": {'+y': 'hay_block_top', '-y': 'hay_block_top', '-z': 'hay_block_side', '+z': 'hay_block_side', '+x': 'hay_block_side', '-x': 'hay_block_side'},
    "infested_deepslate": {'+y': 'deepslate_top', '-y': 'deepslate_top', '-z': 'deepslate', '+z': 'deepslate', '+x': 'deepslate', '-x': 'deepslate'},
    "jack_o_lantern": {'+y': 'pumpkin_top', '-y': 'pumpkin_top', '-z': 'jack_o_lantern', '+z': 'pumpkin_side', '+x': 'pumpkin_side', '-x': 'pumpkin_side'},
    "jigsaw": {'+y': 'jigsaw_lock', '-y': 'jigsaw_side', '-z': 'jigsaw_top', '+z': 'jigsaw_bottom', '+x': 'jigsaw_side', '-x': 'jigsaw_side'},
    "jukebox": {'+y': 'jukebox_top', '-y': 'jukebox_side', '-z': 'jukebox_side', '+z': 'jukebox_side', '+x': 'jukebox_side', '-x': 'jukebox_side'},
    "jungle_log": {'+y': 'jungle_log_top', '-y': 'jungle_log_top', '-z': 'jungle_log', '+z': 'jungle_log', '+x': 'jungle_log', '-x': 'jungle_log'},
    "lodestone": {'+y': 'lodestone_top', '-y': 'lodestone_top', '-z': 'lodestone_side', '+z': 'lodestone_side', '+x': 'lodestone_side', '-x': 'lodestone_side'},
    "loom": {'+y': 'loom_top', '-y': 'loom_bottom', '-z': 'loom_front', '+z': 'loom_side', '+x': 'loom_side', '-x': 'loom_side'},
    "mangrove_log": {'+y': 'mangrove_log_top', '-y': 'mangrove_log_top', '-z': 'mangrove_log', '+z': 'mangrove_log', '+x': 'mangrove_log', '-x': 'mangrove_log'},
    "melon": {'+y': 'melon_top', '-y': 'melon_top', '-z': 'melon_side', '+z': 'melon_side', '+x': 'melon_side', '-x': 'melon_side'},
    "muddy_mangrove_roots": {'+y': 'muddy_mangrove_roots_top', '-y': 'muddy_mangrove_roots_top', '-z': 'muddy_mangrove_roots_side', '+z': 'muddy_mangrove_roots_side', '+x': 'muddy_mangrove_roots_side', '-x': 'muddy_mangrove_roots_side'},
    "mycelium": {'+y': 'mycelium_top', '-y': 'dirt', '-z': 'mycelium_side', '+z': 'mycelium_side', '+x': 'mycelium_side', '-x': 'mycelium_side'},
    "oak_log": {'+y': 'oak_log_top', '-y': 'oak_log_top', '-z': 'oak_log', '+z': 'oak_log', '+x': 'oak_log', '-x': 'oak_log'},
    "observer": {'+y': 'observer_top', '-y': 'observer_top', '-z': 'observer_front', '+z': 'observer_back', '+x': 'observer_side', '-x': 'observer_side'},
    "ochre_froglight": {'+y': 'ochre_froglight_top', '-y': 'ochre_froglight_top', '-z': 'ochre_froglight_side', '+z': 'ochre_froglight_side', '+x': 'ochre_froglight_side', '-x': 'ochre_froglight_side'},
    "pale_oak_log": {'+y': 'pale_oak_log_top', '-y': 'pale_oak_log_top', '-z': 'pale_oak_log', '+z': 'pale_oak_log', '+x': 'pale_oak_log', '-x': 'pale_oak_log'},
    "pearlescent_froglight": {'+y': 'pearlescent_froglight_top', '-y': 'pearlescent_froglight_top', '-z': 'pearlescent_froglight_side', '+z': 'pearlescent_froglight_side', '+x': 'pearlescent_froglight_side', '-x': 'pearlescent_froglight_side'},
    "piston": {'+y': 'piston_side', '-y': 'piston_side', '-z': 'piston_top', '+z': 'piston_bottom', '+x': 'piston_side', '-x': 'piston_side'},
    "podzol": {'+y': 'podzol_top', '-y': 'dirt', '-z': 'podzol_side', '+z': 'podzol_side', '+x': 'podzol_side', '-x': 'podzol_side'},
    "polished_basalt": {'+y': 'polished_basalt_top', '-y': 'polished_basalt_top', '-z': 'polished_basalt_side', '+z': 'polished_basalt_side', '+x': 'polished_basalt_side', '-x': 'polished_basalt_side'},
    "pumpkin": {'+y': 'pumpkin_top', '-y': 'pumpkin_top', '-z': 'pumpkin_side', '+z': 'pumpkin_side', '+x': 'pumpkin_side', '-x': 'pumpkin_side'},
    "purpur_pillar": {'+y': 'purpur_pillar_top', '-y': 'purpur_pillar_top', '-z': 'purpur_pillar', '+z': 'purpur_pillar', '+x': 'purpur_pillar', '-x': 'purpur_pillar'},
    "quartz_block": {'+y': 'quartz_block_top', '-y': 'quartz_block_top', '-z': 'quartz_block_side', '+z': 'quartz_block_side', '+x': 'quartz_block_side', '-x': 'quartz_block_side'},
    "quartz_pillar": {'+y': 'quartz_pillar_top', '-y': 'quartz_pillar_top', '-z': 'quartz_pillar', '+z': 'quartz_pillar', '+x': 'quartz_pillar', '-x': 'quartz_pillar'},
    "red_sandstone": {'+y': 'red_sandstone_top', '-y': 'red_sandstone_bottom', '-z': 'red_sandstone', '+z': 'red_sandstone', '+x': 'red_sandstone', '-x': 'red_sandstone'},
    "reinforced_deepslate": {'+y': 'reinforced_deepslate_top', '-y': 'reinforced_deepslate_bottom', '-z': 'reinforced_deepslate_side', '+z': 'reinforced_deepslate_side', '+x': 'reinforced_deepslate_side', '-x': 'reinforced_deepslate_side'},
    "repeating_command_block": {'+y': 'repeating_command_block_side', '-y': 'repeating_command_block_side', '-z': 'repeating_command_block_front', '+z': 'repeating_command_block_back', '+x': 'repeating_command_block_side', '-x': 'repeating_command_block_side'},
    "respawn_anchor": {'+y': 'respawn_anchor_top_off', '-y': 'respawn_anchor_bottom', '-z': 'respawn_anchor_side0', '+z': 'respawn_anchor_side0', '+x': 'respawn_anchor_side0', '-x': 'respawn_anchor_side0'},
    "sandstone": {'+y': 'sandstone_top', '-y': 'sandstone_bottom', '-z': 'sandstone', '+z': 'sandstone', '+x': 'sandstone', '-x': 'sandstone'},
    "sculk_catalyst": {'+y': 'sculk_catalyst_top', '-y': 'sculk_catalyst_bottom', '-z': 'sculk_catalyst_side', '+z': 'sculk_catalyst_side', '+x': 'sculk_catalyst_side', '-x': 'sculk_catalyst_side'},
    "smithing_table": {'+y': 'smithing_table_top', '-y': 'smithing_table_bottom', '-z': 'smithing_table_front', '+z': 'smithing_table_front', '+x': 'smithing_table_side', '-x': 'smithing_table_side'},
    "smoker": {'+y': 'smoker_top', '-y': 'smoker_bottom', '-z': 'smoker_front', '+z': 'smoker_side', '+x': 'smoker_side', '-x': 'smoker_side'},
    "sniffer_egg": {'-z': 'sniffer_egg_not_cracked_north', '+z': 'sniffer_egg_not_cracked_south', '+x': 'sniffer_egg_not_cracked_east', '-x': 'sniffer_egg_not_cracked_west'},
    "spruce_log": {'+y': 'spruce_log_top', '-y': 'spruce_log_top', '-z': 'spruce_log', '+z': 'spruce_log', '+x': 'spruce_log', '-x': 'spruce_log'},
    "sticky_piston": {'+y': 'piston_side', '-y': 'piston_side', '-z': 'piston_top_sticky', '+z': 'piston_bottom', '+x': 'piston_side', '-x': 'piston_side'},
    "stripped_acacia_log": {'+y': 'stripped_acacia_log_top', '-y': 'stripped_acacia_log_top', '-z': 'stripped_acacia_log', '+z': 'stripped_acacia_log', '+x': 'stripped_acacia_log', '-x': 'stripped_acacia_log'},
    "stripped_bamboo_block": {'+y': 'stripped_bamboo_block', '-y': 'stripped_bamboo_block', '-z': 'stripped_bamboo_block', '+z': 'stripped_bamboo_block', '+x': 'stripped_bamboo_block_top', '-x': 'stripped_bamboo_block_top'},
    "stripped_birch_log": {'+y': 'stripped_birch_log_top', '-y': 'stripped_birch_log_top', '-z': 'stripped_birch_log', '+z': 'stripped_birch_log', '+x': 'stripped_birch_log', '-x': 'stripped_birch_log'},
    "stripped_cherry_log": {'+y': 'stripped_cherry_log', '-y': 'stripped_cherry_log', '-z': 'stripped_cherry_log', '+z': 'stripped_cherry_log', '+x': 'stripped_cherry_log_top', '-x': 'stripped_cherry_log_top'},
    "stripped_crimson_stem": {'+y': 'stripped_crimson_stem_top', '-y': 'stripped_crimson_stem_top', '-z': 'stripped_crimson_stem', '+z': 'stripped_crimson_stem', '+x': 'stripped_crimson_stem', '-x': 'stripped_crimson_stem'},
    "stripped_dark_oak_log": {'+y': 'stripped_dark_oak_log_top', '-y': 'stripped_dark_oak_log_top', '-z': 'stripped_dark_oak_log', '+z': 'stripped_dark_oak_log', '+x': 'stripped_dark_oak_log', '-x': 'stripped_dark_oak_log'},
    "stripped_jungle_log": {'+y': 'stripped_jungle_log_top', '-y': 'stripped_jungle_log_top', '-z': 'stripped_jungle_log', '+z': 'stripped_jungle_log', '+x': 'stripped_jungle_log', '-x': 'stripped_jungle_log'},
    "stripped_mangrove_log": {'+y': 'stripped_mangrove_log_top', '-y': 'stripped_mangrove_log_top', '-z': 'stripped_mangrove_log', '+z': 'stripped_mangrove_log', '+x': 'stripped_mangrove_log', '-x': 'stripped_mangrove_log'},
    "stripped_oak_log": {'+y': 'stripped_oak_log_top', '-y': 'stripped_oak_log_top', '-z': 'stripped_oak_log', '+z': 'stripped_oak_log', '+x': 'stripped_oak_log', '-x': 'stripped_oak_log'},
    "stripped_pale_oak_log": {'+y': 'stripped_pale_oak_log_top', '-y': 'stripped_pale_oak_log_top', '-z': 'stripped_pale_oak_log', '+z': 'stripped_pale_oak_log', '+x': 'stripped_pale_oak_log', '-x': 'stripped_pale_oak_log'},
    "stripped_spruce_log": {'+y': 'stripped_spruce_log_top', '-y': 'stripped_spruce_log_top', '-z': 'stripped_spruce_log', '+z': 'stripped_spruce_log', '+x': 'stripped_spruce_log', '-x': 'stripped_spruce_log'},
    "stripped_warped_stem": {'+y': 'stripped_warped_stem_top', '-y': 'stripped_warped_stem_top', '-z': 'stripped_warped_stem', '+z': 'stripped_warped_stem', '+x': 'stripped_warped_stem', '-x': 'stripped_warped_stem'},
    "target": {'+y': 'target_top', '-y': 'target_top', '-z': 'target_side', '+z': 'target_side', '+x': 'target_side', '-x': 'target_side'},
    "tnt": {'+y': 'tnt_top', '-y': 'tnt_bottom', '-z': 'tnt_side', '+z': 'tnt_side', '+x': 'tnt_side', '-x': 'tnt_side'},
    "trial_spawner": {'+y': 'trial_spawner_top_active', '-y': 'trial_spawner_bottom', '-z': 'trial_spawner_side_active', '+z': 'trial_spawner_side_active', '+x': 'trial_spawner_side_active', '-x': 'trial_spawner_side_active'},
    "vault": {'+y': 'vault_top', '-y': 'vault_bottom', '-z': 'vault_front_on', '+z': 'vault_side_on', '+x': 'vault_side_on', '-x': 'vault_side_on'},
    "verdant_froglight": {'+y': 'verdant_froglight_top', '-y': 'verdant_froglight_top', '-z': 'verdant_froglight_side', '+z': 'verdant_froglight_side', '+x': 'verdant_froglight_side', '-x': 'verdant_froglight_side'},
    "warped_nylium": {'+y': 'warped_nylium', '-y': 'netherrack', '-z': 'warped_nylium_side', '+z': 'warped_nylium_side', '+x': 'warped_nylium_side', '-x': 'warped_nylium_side'},
    "warped_stem": {'+y': 'warped_stem_top', '-y': 'warped_stem_top', '-z': 'warped_stem', '+z': 'warped_stem', '+x': 'warped_stem', '-x': 'warped_stem'},
}
